Repository GoogleCloudPlatform/cloud-sql-jdbc-socket-factory, pull requests merged in 2023-09, with the labels that each got.

#1449 chore(ci): Add all common release configuration from alloydb java
  .github/dependabot.yml
  .github/generated-files-bot.yml
  .github/labels.yml
  .github/sync-repo-settings.yaml
  .gitignore
  .kokoro/build.sh
  .kokoro/release/bump_snapshot.cfg
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/snapshot.cfg
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  .kokoro/requirements.in
  .kokoro/requirements.txt
  .repo-metadata.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  java.header
  license-checks.xml
  owlbot.py
  renovate.json
Labels: size: xl, api: cloudsql

#1452 chore: Remove deprecated connector using the MySQL J5 library.
  jdbc/mysql-j-5/pom.xml
  jdbc/mysql-j-5/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java
  jdbc/mysql-j-5/src/test/java/com/google/cloud/sql/mysql/JdbcMysqlJ5IntegrationTests.java
  pom.xml
Labels: api: cloudsql, size: l

#1454 chore: update blunderbuss
  .github/blunderbuss.yml
Labels: size: xs, api: cloudsql

#1441 fix: re-use existing connection info during force refresh
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
Labels: size: m

#1430 deps: Update dependencies related to netty and r2dbc
  jdbc/mysql-j-8/pom.xml
  r2dbc/core/pom.xml
  r2dbc/mysql/pom.xml
  r2dbc/postgres/pom.xml
  r2dbc/sqlserver/pom.xml
Labels: size: m

#1490 chore: migrate renovate config and group dependencies
  .github/renovate.json
Labels: size: s

#1520 chore: group python dependencies in renovate config
  .github/renovate.json
Labels: size: s, api: cloudsql

#1523 chore: group dependencies for github in renovate config
  .github/renovate.json
Labels: size: s, api: cloudsql

#1540 chore: use Instant instead of Date
  core/src/main/java/com/google/cloud/sql/CredentialFactory.java
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/DefaultAccessTokenSupplier.java
  core/src/main/java/com/google/cloud/sql/core/InstanceData.java
  core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
  core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java
  core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Labels: size: m

#1542 deps: Update dependency graalvm to v23.1.0
  core/pom.xml
  jdbc/mariadb/pom.xml
  jdbc/mysql-j-8/pom.xml
  jdbc/postgres/pom.xml
  jdbc/sqlserver/pom.xml
  pom.xml
  r2dbc/core/pom.xml
  r2dbc/mysql/pom.xml
  r2dbc/postgres/pom.xml
  r2dbc/sqlserver/pom.xml
Labels: size: s, api: cloudsql

#1544 chore: fix lint warnings
  core/pom.xml
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java
  core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
  core/src/test/java/com/google/cloud/sql/core/DefaultAccessTokenSupplierTest.java
  core/src/test/java/com/google/cloud/sql/core/StubApiFetcherFactory.java
  jdbc/mariadb/src/test/java/com/google/cloud/sql/mariadb/JdbcMariaDBIamAuthIntegrationTests.java
  jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java
  pom.xml
Labels: size: m, api: cloudsql
