Repository GoogleCloudPlatform/cloud-sql-jdbc-socket-factory, pull requests merged in 2023-10, with the labels that each got.

#1579 chore: group com.google.auth dependencies in renovate config
  .github/renovate.json
Labels: size: xs, api: cloudsql

#1582 chore: ignore java 8 deprecation warnings.
  pom.xml
Labels: size: xs, api: cloudsql

#1571 test: Testcase improvements for the CloudSqlInstanceTest
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
  core/src/test/java/com/google/cloud/sql/core/PauseCondition.java
Labels: size: l

#1572 test: set timeout for refresh operation in CoreSocketFactory.
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
  core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
  r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
Labels: size: m

#1593 chore: Set project-wide config for CLIRR version compatibility checks
  core/pom.xml
  pom.xml
Labels: api: cloudsql, size: s

#1589 chore: update renovate config to ignore some deps
  .github/renovate.json
Labels: size: xs

#1573 fix: Improve handling of futures and threads during refresh.
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/InstanceDataSupplier.java
  core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
  core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java
  core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Labels: size: l

#1609 chore: configure release-please to update released version in doc files
  docs/jdbc-mariadb.md
  docs/jdbc-mysql.md
  docs/jdbc-postgres.md
  docs/jdbc-sqlserver.md
  docs/r2dbc-mysql.md
  docs/r2dbc-postgres.md
  docs/r2dbc-sqlserver.md
Labels: api: cloudsql, size: s

#1592 chore: Create a connector configuration value object
  core/src/main/java/com/google/cloud/sql/ConnectionConfig.java
  core/src/main/java/com/google/cloud/sql/IpType.java
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/test/java/com/google/cloud/sql/ConnectionConfigTest.java
  core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
  jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
  jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java
  jdbc/sqlserver/src/test/java/com/google/cloud/sql/sqlserver/JdbcSqlServerUnitTests.java
  pom.xml
  r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java
  r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
  r2dbc/mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java
  r2dbc/postgres/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderPostgres.java
  r2dbc/sqlserver/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMssql.java
Labels: size: l, api: cloudsql

#1605 docs: Consolidate all JDBC docs onto one page
  .github/release-please.yml
  README.md
  docs/jdbc-mariadb.md
  docs/jdbc-mysql.md
  docs/jdbc-postgres.md
  docs/jdbc-sqlserver.md
  docs/jdbc.md
  docs/r2dbc.md
Labels: size: xl

#1617 feat: add support for configuring Admin API URL
  core/src/main/java/com/google/cloud/sql/ConnectionConfig.java
  core/src/main/java/com/google/cloud/sql/core/ApiFetcherFactory.java
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcherFactory.java
  core/src/test/java/com/google/cloud/sql/ConnectionConfigTest.java
  core/src/test/java/com/google/cloud/sql/core/MockAdminApi.java
  core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java
  core/src/test/java/com/google/cloud/sql/core/StubApiFetcherFactory.java
  docs/jdbc.md
  docs/r2dbc.md
  r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
Labels: size: l

#1618 refactor: Use IpType instead of String
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/main/java/com/google/cloud/sql/core/InstanceData.java
  core/src/main/java/com/google/cloud/sql/core/Metadata.java
  core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
  core/src/test/java/com/google/cloud/sql/core/SqlAdminApiFetcherTest.java
  core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Labels: size: m

#1574 feat: non-blocking rate limiting on refresh.
  core/pom.xml
  core/src/main/java/com/google/cloud/sql/core/AsyncRateLimiter.java
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/test/java/com/google/cloud/sql/core/AsyncRateLimiterTest.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceConcurrencyTest.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
Labels: size: l

#1615 chore: Extract Refresher from CloudSqlInstance
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/InstanceData.java
  core/src/main/java/com/google/cloud/sql/core/InstanceDataSupplier.java
  core/src/main/java/com/google/cloud/sql/core/Refresher.java
  core/src/main/java/com/google/cloud/sql/core/SqlAdminApiFetcher.java
  core/src/test/java/com/google/cloud/sql/core/PauseCondition.java
  core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Labels: size: l, api: cloudsql

#1640 refactor: Rename SqlAdminApiFetcher to DefaultConnectionInfoRepository
  core/src/main/java/com/google/cloud/sql/core/CloudSqlInstance.java
  core/src/main/java/com/google/cloud/sql/core/ConnectionInfoRepository.java
  core/src/main/java/com/google/cloud/sql/core/ConnectionInfoRepositoryFactory.java
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
  core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepositoryFactory.java
  core/src/test/java/com/google/cloud/sql/core/CloudSqlInstanceTest.java
  core/src/test/java/com/google/cloud/sql/core/CoreSocketFactoryTest.java
  core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoRepositoryTest.java
  core/src/test/java/com/google/cloud/sql/core/StubConnectionInfoRepositoryFactory.java
  core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
  r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
Labels: size: m

#1641 chore: rename CloudSqlInstance to DefaultConnectionInfoCache
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoCache.java
  core/src/main/java/com/google/cloud/sql/core/Refresher.java
  core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheConcurrencyTest.java
  core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheTest.java
Labels: size: m

#1642 chore: rename InstanceData to ConnectionInfo
  core/src/main/java/com/google/cloud/sql/core/ConnectionInfo.java
  core/src/main/java/com/google/cloud/sql/core/ConnectionInfoRepository.java
  core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoCache.java
  core/src/main/java/com/google/cloud/sql/core/DefaultConnectionInfoRepository.java
  core/src/main/java/com/google/cloud/sql/core/Refresher.java
  core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheTest.java
  core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoRepositoryTest.java
  core/src/test/java/com/google/cloud/sql/core/RefresherTest.java
  core/src/test/java/com/google/cloud/sql/core/TestDataSupplier.java
Labels: size: l

#1645 chore: Extract internal connector registry implementation
  core/src/main/java/com/google/cloud/sql/core/CoreSocketFactory.java
  core/src/main/java/com/google/cloud/sql/core/InternalConnectorRegistry.java
  core/src/main/java/com/google/cloud/sql/core/package-info.java
  core/src/test/java/com/google/cloud/sql/core/DefaultConnectionInfoCacheConcurrencyTest.java
  core/src/test/java/com/google/cloud/sql/core/InternalConnectorRegistryTest.java
  jdbc/mariadb/src/main/java/com/google/cloud/sql/mariadb/SocketFactory.java
  jdbc/mysql-j-8/src/main/java/com/google/cloud/sql/mysql/SocketFactory.java
  jdbc/postgres/src/main/java/com/google/cloud/sql/postgres/SocketFactory.java
  jdbc/sqlserver/src/main/java/com/google/cloud/sql/sqlserver/SocketFactory.java
  r2dbc/core/src/main/java/com/google/cloud/sql/core/CloudSqlConnectionFactory.java
  r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java
  r2dbc/core/src/test/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderTest.java
  r2dbc/mysql/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMysql.java
  r2dbc/postgres/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderPostgres.java
  r2dbc/sqlserver/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProviderMssql.java
Labels: size: l
